### ISSUE TITLE
Having trouble installing; missing items?

### ISSUE THREAD

**Issue by jkantner** [gmattie/Data-Pixels#1]
I tried compiling the production code in the project folder using `npm run prod` as the readme says, and I keep getting this:

```
> gulp --production

module.js:472
    throw err;
    ^

Error: Cannot find module 'autoprefixer'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jon/Downloads/Data-Pixels-master/gulpfile.js:2:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "prod"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! data-pixels-playground@1.0.0 prod: `gulp --production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the data-pixels-playground@1.0.0 prod script 'gulp --production'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the data-pixels-playground package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp --production
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs data-pixels-playground
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls data-pixels-playground
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jon/.npm/_logs/2017-05-20T13_59_22_864Z-debug.log

```
I even have the latest version of Node.js, npm, and gulp installed. For help, I tried `npm bugs data-pixels-playground` and `npm owner ls data-pixels-playground`, but I got 404 errors.

The packaging commands relevant to my OS won’t work either, and I was in the build folder. I get `missing script` errors for package and package-mac.

**Comment by gmattie** [comment]
In the package.json file there's a list of development dependencies that need to be installed before compiling the code.  Try running the following CLI command at the root folder before compiling:

`npm install`

This step of installing development dependencies must also be done in the build folder before trying to package the application.

**Comment by jkantner** [comment]
Okay, I got everything to work now. Thanks!
