### ISSUE TITLE
"Error: Command failed..."

### ISSUE THREAD

**Issue by danielkuhlwein** [gmattie/Data-Pixels#4]
First I run `npm run prod` then `cd resources/build` 

After that, running either `npm run package` or `npm run package-mac` results in the following error:

`{ Error: Command failed: electron-packager ./ --overwrite --asar --arch=x64 --app-copyright="Copyright © 2017 Geoffrey Mattie" --out="./releases/" --platform=darwin --app-bundle-id=com.mattie.DataPixelsPlayground --icon=../source/images/icons/icon.icns
/bin/sh: electron-packager: command not found
at ChildProcess.exithandler (child_process.js:198:12)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:891:16)
at Socket.<anonymous> (internal/child_process.js:342:11)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at Pipe._handle.close [as _onclose] (net.js:497:12)
killed: false,
code: 127,
signal: null,
cmd: 'electron-packager ./ --overwrite --asar --arch=x64 --app-copyright="Copyright © 2017 Geoffrey Mattie" --out="./releases/" --platform=darwin --app-bundle-id=com.mattie.DataPixelsPlayground --icon=../source/images/icons/icon.icns' }`

**Comment by chris-c-thomas** [comment]
I just came across this app and found it very intriguing. @danielkuhlwein I'm also on a Mac (MacOS 10.13.1) and am receiving the exact same errors.

Download and unzip. 

`npm install`

`npm run prod`

`cd resources/build`

`npm run package-mac` or `npm run package` gives me:

    { Error: Command failed: electron-packager ./ --overwrite --asar --arch=x64 --app-copyright="Copyright © 2017 Geoffrey Mattie" --out="./releases/" --platform=darwin --app-bundle-id=com.mattie.DataPixelsPlayground --icon=../source/images/icons/icon.icns
    /bin/sh: electron-packager: command not found

        at ChildProcess.exithandler (child_process.js:275:12)
        at emitTwo (events.js:126:13)
        at ChildProcess.emit (events.js:214:7)
        at maybeClose (internal/child_process.js:925:16)
        at Socket.stream.socket.on (internal/child_process.js:346:11)
        at emitOne (events.js:116:13)
      at Socket.emit (events.js:211:7)
      at Pipe._handle.close [as _onclose] (net.js:554:12)
    killed: false,
    code: 127,
    signal: null,
    cmd: 'electron-packager ./ --overwrite --asar --arch=x64 --app-copyright="Copyright © 2017Geoffrey Mattie" --out="./releases/" --platform=darwin --app-bundle-id=com.mattie.DataPixelsPlayground --icon=../source/images/icons/icon.icns' }
